// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // `prisma generate` can run in CI/CD without DIRECT_URL, so avoid env()
    // and keep an empty-string fallback to let the config load.
    // Migrations still need DIRECT_URL when you actually run them.
    url: process.env.DIRECT_URL ?? "",
  },
});
